### ISSUE TITLE
Graph Construction Report

### ISSUE THREAD

**Issue by clsid2** [cplussharp/graph-studio-next#271]
The current log does not show any details about the source filter.

When a filter is created, but pin connection fails, and filter is thus not used, this is also not reflected in the log.

**Comment by mikecopperwhite** [comment]
Thanks for the report. Can you provide a few more pointers to reproduce the problem please?

**Comment by mikecopperwhite** [comment]
I've looked at the code. The graph construction report is using all of the information provided to IAMGraphBuilderCallback. It seems to be a limitation of DirectShow that IAMGraphBuilderCallback does not report source filters probably because of the different method used for selecting source and parser filters (see "Registering a Custom File Type" in MSDN documentation).

The alternative is to look at the DirectShow Unicode log file (File/Set Log File... in Graph Studio Next) or possibly an external tool like FilterGraph Spy. There is another issue for improvements to make the log file more usable #230. 

I'm closing this issue for now unless there are suggestions for getting more information via IAMGraphBuilderCallback.

**Comment by mikecopperwhite** [comment]
The callbacks we receive are
Filter Selected
Filter Created
Render Pin failed.

There is no callback to reflect that a created filter can't be connected.
