### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by datgith** [cplussharp/graph-studio-next#345]
Can't download any releases, why?

**Comment by tokyojoe90** [comment]
Looks like a permissions issue

**Comment by cplussharp** [comment]
The old releases are all still pointing to the old repository hoster: code.google.com. (that is long gone)
I also cant't download the files of the "current" release 0.7.0.430 (2014-11-10) as google says that have I virus? (Probably a false positive has these files have not been changed since 2014!)
I think the best would be to create a new official release with the current changes and store it this time as github release.

**Comment by rdp** [comment]
+1 appveyor says "{"message":"Artifact not found or access denied."}"

**Comment by cplussharp** [comment]
Sadly the last build is always removed after 4 weeks or so by appveyor.
Please use the official release you can find on the github release page: https://github.com/cplussharp/graph-studio-next/releases

**Comment by rdp** [comment]
Maybe could update the readme links to it?  Thanks :)
